collections:
  blog: '/blog/{slug}'
  things: '/things/{slug}'
taxonomies:
  tags: '/blog/tags/{slug}'
routes:
  /blog/tags: blog/taxonomies
  /search: search
  /blog/feed:
    layout: feed
    template: feeds/blog
    content_type: atom
  /things/feed:
    layout: feed
    template: feeds/things
    content_type: atom
